// Draft-only regression check. Set AUTH_STATE and optionally BASE_URL,
// PLAYWRIGHT_MODULE, and COTTAGE_SOURCE (local integration preview).
import assert from 'node:assert/strict';
import path from 'node:path';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true});
try {
  const context = await browser.newContext({storageState: process.env.AUTH_STATE, viewport: {width: 1440, height: 1000}});
  if (process.env.COTTAGE_SOURCE) await context.route('https://cottage616-production.up.railway.app/**', route => {
    const file = new URL(route.request().url()).pathname.slice(1);
    if (['scripts/site.js', 'scripts/integrations/showrunner/content.js', 'scripts/integrations/showrunner/editor.js', 'styles/site.css'].includes(file)) return route.fulfill({path: path.join(process.env.COTTAGE_SOURCE, file), contentType: file.endsWith('.js') ? 'text/javascript' : 'text/css'});
    return route.continue();
  });
  const page = await context.newPage();
  page.setDefaultTimeout(60000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const base = process.env.BASE_URL || 'https://showrunner-beta-production.up.railway.app';
  await page.goto(`${base}/admin/modules/content`, {waitUntil: 'domcontentloaded', timeout: 120000});
  const site = page.frameLocator('iframe');
  await site.locator('[data-sr-section="home-hero"]').waitFor({state: 'attached'});
  await page.getByRole('combobox', {name: 'Select section', exact: true}).selectOption('home-hero');
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Close section settings');
  const inspector = page.getByRole('complementary', {name: 'Section settings'});
  const title = inspector.getByRole('textbox', {name: 'Title', exact: true}).first();
  const original = await title.inputValue();
  await title.fill(`${original} audit draft`);
  let warned = false;
  page.once('dialog', async dialog => { warned = true; await dialog.dismiss(); });
  await page.getByRole('link', {name: 'Home', exact: true}).click();
  assert.ok(warned, 'admin navigation warns about unpublished changes');
  assert.ok(page.url().endsWith('/admin/modules/content'));
  assert.equal(await title.inputValue(), `${original} audit draft`);
  await inspector.getByRole('button', {name: 'Choose an image', exact: true}).first().click();
  const modal = page.locator('dialog[open]');
  await modal.waitFor();
  const box = await modal.boundingBox();
  await page.mouse.click(box.x + 3, box.y + box.height / 2);
  assert.equal(await modal.count(), 1, 'dialog padding is not the backdrop');
  await page.keyboard.press('Escape');
  assert.equal(await modal.count(), 0);
  await title.fill(original);
  await title.press('Escape');
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Select section');
  await page.getByRole('combobox', {name: 'Page', exact: true}).selectOption('hive');
  await site.locator('[data-sr-section="hive-hero"]').waitFor({state: 'attached'});
  await page.getByRole('combobox', {name: 'Page', exact: true}).selectOption('home');
  await site.locator('[data-sr-section="home-hero"]').waitFor({state: 'attached'});
  const inactive = site.locator('.sr-hero-screen:not(.is-active)');
  assert.ok(await inactive.evaluateAll(nodes => nodes.every(node => node.inert && node.getAttribute('aria-hidden') === 'true')));
  await page.setViewportSize({width: 390, height: 844});
  await page.getByRole('button', {name: 'Open admin menu', exact: true}).click();
  await page.waitForFunction(() => document.activeElement?.classList.contains('admin-sidebar-close'));
  assert.ok(await page.locator('main').evaluate(node => node.inert));
  await page.keyboard.press('Shift+Tab');
  assert.ok(await page.locator('#admin-sidebar').evaluate(node => node.contains(document.activeElement)));
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('main').evaluate(node => node.inert), false);
  assert.equal(await page.evaluate(() => document.activeElement.getAttribute('aria-label')), 'Open admin menu');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await site.locator('.menu-toggle').click();
  await site.locator('.menu-toggle').press('Escape');
  assert.equal(await site.locator('.menu-toggle').getAttribute('aria-expanded'), 'false');
  await page.setViewportSize({width: 1440, height: 1000});
  await page.goto(`${base}/admin/modules/scheduling`, {waitUntil: 'load', timeout: 120000});
  const category = page.getByRole('combobox', {name: 'Category', exact: true});
  await category.press('ArrowDown');
  await page.waitForFunction(() => document.getElementById('services-category-filter')?.getAttribute('aria-expanded') === 'true');
  assert.equal(await category.getAttribute('aria-expanded'), 'true');
  const activeOption = await category.getAttribute('aria-activedescendant');
  assert.ok(await page.locator(`[id="${activeOption}"]`).count());
  await category.press('Home');
  await category.press('Escape');
  assert.equal(await category.getAttribute('aria-expanded'), 'false');
  assert.ok(await category.evaluate(node => node === document.activeElement));
  await category.press('Enter');
  await category.press('Tab');
  assert.equal(await category.getAttribute('aria-expanded'), 'false');
  assert.deepEqual(errors, []);
  console.log('PASS: draft protection, inspector focus, modal dismissal, page navigation, hidden slides, mobile keyboard navigation, filter keyboard controls, and overflow. No content published.');
} finally {
  await browser.close();
}
