// Run against a disposable/beta Showrunner instance. Creates a draft album; prints its ID for cleanup.
// ALBUM_TEST_URL, ALBUM_TEST_USER and ALBUM_TEST_PASSWORD must be set.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url);
const sharp = require('sharp');
const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const base = process.env.ALBUM_TEST_URL;
assert(base && process.env.ALBUM_TEST_USER && process.env.ALBUM_TEST_PASSWORD);
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const imageRequests = []; page.on('request', request => { if (request.resourceType() === 'image') imageRequests.push(request.url()); });
const errors = []; page.on('pageerror', error => errors.push(error.message));
page.setDefaultTimeout(45000);
async function submitGalleryAction(name) {
  const [response] = await Promise.all([
    page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/admin/modules/portfolio'),
    page.getByRole('button', { name, exact: true }).click()
  ]);
  assert(response.ok(), name + ' must succeed');
  await response.finished();
}

try {
  await page.goto(`${base}/admin/modules/portfolio`);
  await page.locator('input[name=email]').fill(process.env.ALBUM_TEST_USER);
  await page.locator('input[name=password]').fill(process.env.ALBUM_TEST_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.waitForURL(url => !url.pathname.includes('login'));
  await page.goto(`${base}/admin/modules/portfolio`);
  await page.getByRole('heading', { name: 'Photo albums', exact: true }).waitFor();
  await page.locator('section[aria-label="Photo albums"] img').evaluateAll(images => Promise.all(images.map(image => image.decode())));
  await page.screenshot({ path: '.impeccable/review/albums-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.impeccable/review/albums-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'Open Special Occasions', exact: true }).click();
  await page.getByRole('heading', { name: 'Special Occasions', exact: true }).waitFor();
  await page.getByRole('region', { name: 'Album photos', exact: true }).locator('img').first().waitFor();
  assert.equal(await page.getByRole('region', { name: 'Album photos', exact: true }).locator('button:has(img)').count(), 9);
  const initialImages = await page.getByRole('region', { name: 'Album photos', exact: true }).locator('img').evaluateAll(async images => {
    await Promise.all(images.map(image => image.decode()));
    return images.map(image => ({ src: image.currentSrc, width: image.naturalWidth }));
  });
  assert(initialImages.every(image => image.width <= 720), 'The grid must load thumbnail-sized files');
  const gridPaths = new Set(initialImages.map(image => new URL(image.src).pathname));
  assert(!imageRequests.some(src => { const url = new URL(src); return gridPaths.has(url.pathname) && url.searchParams.get('variant') === 'FULL'; }), 'Full images must not load before opening the viewer');
  await page.getByRole('region', { name: 'Album photos', exact: true }).locator('button:has(img)').first().click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('dialog').locator('img').evaluate(image => image.decode());
  await page.keyboard.press('ArrowRight');
  await page.getByRole('dialog').getByText('2 / 9', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Next photo', exact: true }).dblclick();
  await page.getByRole('dialog').getByText('4 / 9', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.getSelection()?.toString()), '');
  assert.equal(await page.getByRole('dialog').locator('img').evaluate(image => image.draggable), false);
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'All albums', exact: true }).click();
  await page.getByRole('button', { name: 'New album', exact: true }).click();
  const title = `Album check ${Date.now()}`;
  assert.equal(await page.getByRole('dialog').locator('[name=visibility], [name=proofingEnabled], [name=downloadEnabled], [name=accessCode]').count(), 0);
  await page.getByLabel('Album title', { exact: true }).fill(title);
  await page.getByRole('button', { name: 'Create album', exact: true }).click();
  await page.getByRole('heading', { name: title, exact: true }).waitFor();
  const id = new URL(page.url()).searchParams.get('gallery');
  console.log(`TEST_ALBUM_ID=${id}`);
  assert(id);
  await page.getByRole('img', { name: '0 photos', exact: true }).waitFor();
  await page.getByRole('heading', { name: 'Your album starts here', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  assert.equal(await page.getByRole('dialog').getByRole('tab').count(), 0);
  assert.equal(await page.getByRole('dialog').locator('[name=proofingEnabled], [name=downloadEnabled], [name=recipientEmail], [name=accessToken]').count(), 0);
  const saveSettings = page.getByRole('button', { name: 'Save gallery settings', exact: true });
  assert(await saveSettings.evaluate(button => button.form?.getAttribute('id') === 'gallery-settings-form'), 'Pinned save must target the settings form');
  for (const width of [1192, 390]) {
    await page.setViewportSize({ width, height: 792 });
    const scroll = page.getByRole('dialog').locator('[class*="settingsScroll"]');
    await scroll.evaluate(el => el.scrollTop = 0);
    const initialSave = await saveSettings.boundingBox();
    assert(initialSave.y >= 0 && initialSave.y + initialSave.height <= 792, 'Save must be visible immediately');
    await scroll.evaluate(el => el.scrollTop = el.scrollHeight);
    const scrolledSave = await saveSettings.boundingBox();
    assert.equal(scrolledSave.y, initialSave.y, 'Save must stay pinned while settings scroll');
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByLabel('Album title', { exact: true }).fill(title + ' renamed');
  await page.getByLabel('Gallery layout', { exact: true }).selectOption('MASONRY');
  for (const name of ['Published']) await page.getByRole('switch', { name, exact: true }).check();
  await submitGalleryAction('Save gallery settings');
  await page.getByRole('heading', { name: title + ' renamed', exact: true }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  assert.equal(await page.getByLabel('Gallery layout', { exact: true }).inputValue(), 'MASONRY');
  for (const name of ['Published']) {
    assert(await page.getByRole('switch', { name, exact: true }).isChecked());
    await page.getByRole('switch', { name, exact: true }).uncheck();
  }
  await page.getByLabel('Gallery layout', { exact: true }).selectOption('GRID');
  await submitGalleryAction('Save gallery settings');
  await page.getByRole('status').filter({ hasText: 'Album changes saved.' }).first().waitFor();
  await page.reload();
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  assert.equal(await page.getByLabel('Gallery layout', { exact: true }).inputValue(), 'GRID');
  for (const name of ['Published']) assert.equal(await page.getByRole('switch', { name, exact: true }).isChecked(), false);
  await page.locator('summary').filter({ hasText: /^Archive gallery$/ }).click();
  await page.getByRole('switch', { name: 'Confirm archive', exact: true }).check();
  await submitGalleryAction('Archive gallery');
  await page.reload();
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  assert(await page.getByRole('switch', { name: 'Published', exact: true }).isDisabled());
  await submitGalleryAction('Save gallery settings');
  await page.reload();
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  assert(await page.getByRole('switch', { name: 'Published', exact: true }).isDisabled(), 'Saving settings must preserve archived status');
  await page.locator('summary').filter({ hasText: /^Restore gallery$/ }).click();
  await submitGalleryAction('Restore draft');
  await page.getByRole('switch', { name: 'Published', exact: true }).waitFor({ state: 'visible' });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Draft — publish gallery', exact: true }).hover();
  await page.getByRole('tooltip').filter({ hasText: 'Draft — publish gallery' }).waitFor();
  await page.getByRole('button', { name: 'Draft — publish gallery', exact: true }).click();
  await page.getByRole('button', { name: 'Published (public) — switch to draft', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Published (public) — switch to draft', exact: true }).click();
  await page.getByRole('button', { name: 'Draft — publish gallery', exact: true }).waitFor();
  const image = await sharp({ create: { width: 480, height: 320, channels: 3, background: '#116466' } }).png().toBuffer();
  const droppedFiles = await page.evaluateHandle(base64 => {
    const bytes = Uint8Array.from(atob(base64), character => character.charCodeAt(0));
    const transfer = new DataTransfer();
    transfer.items.add(new File([bytes], 'album-check-one.png', { type: 'image/png' }));
    transfer.items.add(new File([bytes], 'album-check-two.png', { type: 'image/png' }));
    transfer.items.add(new File(['not an image'], 'invalid-photo.txt', { type: 'text/plain' }));
    return transfer;
  }, image.toString('base64'));
  await page.getByRole('region', { name: 'Album photos', exact: true }).dispatchEvent('dragenter', { dataTransfer: droppedFiles });
  await page.getByText('Drop photos to upload', { exact: true }).waitFor();
  await page.getByRole('region', { name: 'Album photos', exact: true }).dispatchEvent('drop', { dataTransfer: droppedFiles });
  await droppedFiles.dispose();
  await page.getByRole('status').filter({ hasText: '2 photos added; 1 not uploaded.' }).waitFor({ timeout: 120000 });
  await page.getByRole('alert').filter({ hasText: 'Choose a JPG' }).waitFor();
  await page.getByRole('region', { name: 'Album photos', exact: true }).locator('img').nth(1).waitFor();
  await page.getByRole('region', { name: 'Album photos', exact: true }).locator('img').evaluateAll(images => Promise.all(images.map(image => image.decode())));
  assert.equal(await page.getByRole('region', { name: 'Album photos', exact: true }).locator('button:has(img)').count(), 2);
  await page.reload();
  await page.getByRole('img', { name: '2 photos', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  await page.locator('summary').filter({ hasText: /^Add image from media or URL$/ }).click();
  assert.equal(await page.getByRole('dialog').locator('[name=type], [name=isDownloadable], [name=isWatermarked], [name=licenseNotes]').count(), 0);
  const imageSelect = page.getByLabel('Uploaded image', { exact: true });
  const imageId = await imageSelect.locator('option').nth(1).getAttribute('value');
  await imageSelect.selectOption(imageId);
  await page.getByLabel('Title', { exact: true }).fill('Imported website image');
  await submitGalleryAction('Add image');
  await page.keyboard.press('Escape');
  await page.getByRole('img', { name: '3 photos', exact: true }).waitFor();
  await page.getByRole('link', { name: 'All albums', exact: true }).click();
  const book = page.getByRole('link', { name: `Open ${title} renamed`, exact: true });
  await book.locator('img').evaluate(image => image.decode());
  await page.getByRole('link', { name: 'Open Special Occasions', exact: true }).click();
  await page.getByRole('heading', { name: 'Special Occasions', exact: true }).waitFor();
  await page.getByRole('region', { name: 'Album photos', exact: true }).locator('img').nth(8).waitFor();
  await page.getByRole('region', { name: 'Album photos', exact: true }).locator('img').evaluateAll(images => Promise.all(images.map(image => image.decode())));
  assert.equal(await page.getByRole('heading', { name: 'Start revision round', exact: true }).count(), 0);
  const photoRatios = await page.getByRole('region', { name: 'Album photos', exact: true }).locator('img').evaluateAll(images => images.map(image => ({actual: image.clientWidth / image.clientHeight, natural: image.naturalWidth / image.naturalHeight})));
  assert.equal(photoRatios.length, 9);
  assert.equal(await page.getByRole('region', { name: 'Album photos', exact: true }).locator('header p').count(), 0);
  assert.equal(await page.getByRole('region', { name: 'Album photos', exact: true }).locator('button:has(img)').first().evaluate(button => getComputedStyle(button).cursor), 'default');
  assert(photoRatios.every(ratio => Math.abs(ratio.actual - 1) < .02), 'Management thumbnails must form a consistent square grid');
  assert(await page.getByRole('region', { name: 'Album photos', exact: true }).locator('button:has(img)').evaluateAll(nodes => nodes.every(node => getComputedStyle(node).borderRadius === '0px')), 'Photo thumbnails must have square corners');
  const density = page.getByRole('button', { name: 'Large thumbnails', exact: true });
  const firstThumbnail = page.getByRole('region', { name: 'Album photos', exact: true }).locator('button:has(img)').first();
  const compactWidth = (await firstThumbnail.boundingBox()).width;
  assert.equal(await density.getAttribute('aria-pressed'), 'false');
  await density.click();
  assert.equal(await density.getAttribute('aria-pressed'), 'true');
  assert((await firstThumbnail.boundingBox()).width > compactWidth, 'Large thumbnails must visibly increase the grid size');
  await density.click();
  assert.equal(await density.getAttribute('aria-pressed'), 'false');
  assert.equal((await firstThumbnail.boundingBox()).width, compactWidth);
  await page.screenshot({ path: '.impeccable/review/album-open-desktop.png', fullPage: true });
  await page.getByRole('region', { name: 'Album photos', exact: true }).locator('button:has(img)').first().click();
  await page.getByRole('dialog').locator('img').evaluate(image => image.decode());
  assert(await page.getByRole('dialog').evaluate(dialog => dialog.clientWidth >= innerWidth - 2));
  await page.screenshot({ path: '.impeccable/review/album-viewer-desktop.png', fullPage: true });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  assert.equal(await page.getByRole('dialog').getByText(/Private access|Revision rounds|Client experience|Feedback|Delivery and export/).count(), 0);
  assert.equal(await page.getByRole('dialog').getByRole('switch').count(), 1);
  await page.screenshot({ path: '.impeccable/review/album-settings-desktop.png', fullPage: true });
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 900, height: 900 });
  await page.screenshot({ path: '.impeccable/review/album-open-900.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.impeccable/review/album-open-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Gallery settings', exact: true }).click();
  assert(await page.getByRole('dialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth));
  await page.screenshot({ path: '.impeccable/review/album-settings-mobile.png', fullPage: false });
  await page.keyboard.press('Escape');
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors, []);
  console.log('Verified books, existing photos, draft creation, rename, drag-and-drop upload, publish/draft toggling, selection-free repeated viewer clicks, invalid-file feedback, automatic cover, persistence, keyboard browsing, desktop/mobile, and zero page errors.');
} finally { await browser.close(); }
