ALTER TABLE "Form" ADD COLUMN "enableSteps" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "FormField" ADD COLUMN "conditionalLogic" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "FormField" ADD COLUMN "pageNumber" INTEGER NOT NULL DEFAULT 1;
