-- Keep the initial tenant/site boundary migration's DEFAULT 'site' backfill,
-- then remove the runtime defaults so future multi-site writes must pass siteId.

ALTER TABLE "AnalyticsEvent" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "AnalyticsGoal" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Automation" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "AvailabilityRule" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "BillingDocument" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "BlockedTime" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Booking" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Cart" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Client" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Collection" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Coupon" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailCampaign" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailOutbox" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailProviderEvent" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailRecipientGroup" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailSenderIdentity" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailSendingDomain" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailSubscriber" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "EmailSubscriptionList" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Form" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "MediaAsset" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "MessageLog" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "MessageTemplate" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "ModuleInstallation" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "ModuleSetting" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Order" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "PortfolioGallery" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "PortfolioGalleryAccess" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Product" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "PublicRateLimit" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Service" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "SiteSettings" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "SuppressionListEntry" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "Testimonial" ALTER COLUMN "siteId" DROP DEFAULT;
ALTER TABLE "WebhookEndpoint" ALTER COLUMN "siteId" DROP DEFAULT;
